return {
  { 'comfysage/chaivim', dir = core.path.core },
  { 'folke/lazy.nvim' },
  { name = 'keymaps', 'comfysage/keymaps.nvim' },
  { name = 'yosu', 'comfysage/yosu.nvim' },
  { 'comfysage/base46',
    cond = function() return core.config.ui.base46 ~= nil and core.config.ui.colorscheme == 'base46' end },
  { name = 'plenary', 'nvim-lua/plenary.nvim' },
  { name = 'telescope', 'nvim-telescope/telescope.nvim',
    dependencies = {
      { 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' },
      { 'nvim-telescope/telescope-ui-select.nvim' },
    },
  },
  { name = 'telescope_fzf', 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' },
  { name = 'telescope_select', 'nvim-telescope/telescope-ui-select.nvim' },
  { name = 'lualine', 'nvim-lualine/lualine.nvim',
    cond = function() return core.lib.options:enabled 'lualine' end },
  { 'comfysage/evergarden' },
  { name = 'treesitter', 'nvim-treesitter/nvim-treesitter',
    version = false, -- last release is way too old and doesn't work on Windows
    build = ":TSUpdate",
  },
  {
    'hrsh7th/nvim-cmp',
    'hrsh7th/cmp-nvim-lsp',
    'hrsh7th/cmp-nvim-lua',
    { 'hrsh7th/cmp-buffer', 'hrsh7th/cmp-path', 'hrsh7th/cmp-cmdline' },
  },
  { name = 'lspconfig', 'neovim/nvim-lspconfig' },
  { name = 'luasnip', 'L3MON4D3/LuaSnip',
    cond = function() return core.lib.options:enabled 'luasnip' end,
    version = 'v2.*',
    dependencies = {
      'saadparwaiz1/cmp_luasnip',
      'rafamadriz/friendly-snippets',
    },
  },
  { name = 'null', 'nvimtools/none-ls.nvim' },
  { name = 'mini', 'echasnovski/mini.nvim' },
  { name = 'gitsigns', 'lewis6991/gitsigns.nvim' },
  { name = 'whichkey', 'folke/which-key.nvim',
    cond = function() return core.lib.options:enabled 'whichkey' end },
  { name = 'todo_comments', 'folke/todo-comments.nvim',
    dependencies = 'nvim-lua/plenary.nvim',
    cond = function() return core.lib.options:enabled 'todo_comments' end },
  { name = 'trouble', 'folke/trouble.nvim',
    cond = function() return core.lib.options:enabled 'trouble' end },
  { name = 'incline', 'b0o/incline.nvim',
    cond = function() return core.lib.options:enabled 'incline' end },
  { name = 'indent', 'lukas-reineke/indent-blankline.nvim',
    cond = function() return core.lib.options:enabled 'indent' end },
  { name = 'fidget', 'j-hui/fidget.nvim',
    cond = function() return core.lib.options:enabled 'fidget' end },
  { 'nvim-tree/nvim-web-devicons',
    cond = function() return core.config.ui.devicons end },
  { import = core.config.plugins },
}
